# -*- coding: utf-8 -*-
"""PythonFaixaPreta3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQ6V_3gmH0hBaN-ymb3YZs-UQxby_gaK
"""

temperatura = 'frio'  #'quente'

print(temperatura)

if temperatura == 'quente':
  print('Vou ir tomar sorvete')
  print('Vou para a praia')
else:
  print('Vou comer um chocolate!')
  print('Vamos assistir The Boys')

horario = 'noite'

if horario == 'manhã':
  print('O sol esta quente')
elif horario == 'tarde':
  print('O por do sol esta chegando!')
else:
  print('A noite esta linda')

idade = 23

if idade <= 18:
  print('Você já pode beber, mas com moderação')
else:
  print('Você não pode beber')

for n in range(10):
  print('agora o numero está no: ', n)

nomes = ['Felipe', 'Fabiane', 'Paulo', 'Katia']

for nome in nomes:
  print('O nome atual é: ', nome)
  if nome == 'Felipe':
    print('Ou Zarcky')

notas = [3, 5, 5, 6]

soma = 0

for nota in notas:
  soma = soma + nota

print('A soma é de : ', soma)

media = soma / len(notas)

print('A média é de: ', media)

def calc_media (nota1, nota2):
  media = (nota1 + nota2)/2
  print(media)

media_calculada = calc_media(10,15)

print(media_calculada)

def numero_quadrado(numero):
  quadrado = numero * numero
  return quadrado

def calcular_imc (peso, altura):
  altura_quadrada = numero_quadrado(altura)
  meu_imc = peso/ altura_quadrada
  return meu_imc

def class_imc(meu_imc):
  if imc < 18.5:
    print('Magreza')
  elif imc >= 18.5 and imc < 25:
    print('Normal')
  elif imc >= 25 and imc < 30:
    print('Sobrepeso')
  elif imc >= 30 and imc < 40:
    print('Obesidade')
  else:
    print('Obesidade Grave')

imc = calcular_imc(66,1.75)
print('Seu IMC é: ', imc)

print('sua classificação é: ')
class_imc(imc)

